baseURL: https://www.apollo-roboto.dev/
languageCode: en-us
defaultContentLanguage: en
title: Apollo-Roboto
theme: customTheme

enableGitInfo: true
copyright: Apollo-Roboto
summaryLength: 70
enableEmoji: true
enableInlineShortcodes: true
googleAnalytics: G-99E0KYVB3G
rssLimit: null
paginate: 5

author:
  name: Apollo Roboto
  email: Apollo_Roboto@outlook.com

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3

markup:
  highlight:
    noClasses: false
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

params:
  debug: false
  pride: false
  githubIssueUrl: https://github.com/Apollo-Roboto/Apollo-Roboto.dev/issues/new/choose
  socials:
    - name: GitHub
      url: https://github.com/Apollo-Roboto
      userName: Apollo-Roboto
      iconUrl: /images/GitHub_Icon.svg
    - name: StackOverflow
      url: https://stackoverflow.com/users/10101321/apollo-roboto
      userName: Apollo-Roboto
      iconUrl: /images/StackOverflow_Icon.svg
    - name: Ko-fi
      url: https://ko-fi.com/M4M3CMENQ
      userName: Apollo-Roboto
      iconUrl: /images/Ko-fi_Icon.svg
    - name: Email
      url: mailto:Apollo_Roboto@outlook.com
      userName: Apollo_Roboto@outlook.com
      iconUrl: /images/Email_Icon.svg
    - name: RSS
      url: https://www.apollo-roboto.dev/index.xml
      userName: Click Here
      iconUrl: /images/RSS_Icon.svg