baseURL: https://www.apollo-roboto.dev/
languageCode: en-us
defaultContentLanguage: en
title: ApolloRoboto
theme: custom_theme
copyright: ApolloRoboto

params:
  author:
    name: Alexandre Thibessart
    email: alexandre.thibessart@outlook.com
  debug: false
  visual_effects: true
  pride: false
  github_issue_url: https://github.com/Apollo-Roboto/apollo-roboto.dev/issues/new/choose
  socials:
    - name: GitHub
      shown: true
      url: https://github.com/Apollo-Roboto
      text: Apollo-Roboto
      icon_url: /images/GitHub_Icon.svg
    - name: StackOverflow
      shown: false
      url: https://stackoverflow.com/users/10101321/apolloroboto
      text: ApolloRoboto
      icon_url: /images/StackOverflow_Icon.svg
    - name: Ko-fi
      shown: true
      url: https://ko-fi.com/apolloroboto
      text: Buy me a coffee!
      icon_url: /images/Ko-fi_Icon.svg
    - name: LinkedIn
      shown: true
      url: https://www.linkedin.com/in/alexandre-thibessart-a63837181/
      text: Alexandre Thibessart
      icon_url: /images/LinkedIn_Icon.svg
    - name: Buymeacoffee
      shown: false
      url: https://www.buymeacoffee.com/ApolloRoboto
      text: Buy me a coffee!
      icon_url: /images/buymeacoffee_Icon.svg
    - name: Email
      shown: true
      url: mailto:alexandre.thibessart@outlook.com
      text: alexandre.thibessart@outlook.com
      icon_url: /images/Email_Icon.svg
    - name: RSS
      shown: true
      url: https://www.apollo-roboto.dev/index.xml
      text: Subscribe
      icon_url: /images/RSS_Icon.svg

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Projects
      url: "/#projects"
      weight: 2
    - name: Socials
      url: "/#socials"
      weight: 3

ignoreFiles:
  - 'content.*\.xcf$' # for the thumbnail gimp files

mainSections: []

enableGitInfo: true
summaryLength: 70
enableEmoji: true
enableInlineShortcodes: true
rssLimit: null
paginate: 6
enableRobotsTXT: true

services:
  googleAnalytics:
    id: G-99E0KYVB3G

privacy:
  googleAnalytics:
    disable: false
    respectDoNotTrack: true

markup:
  highlight:
    noClasses: false
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

# for gitub pages deployments
# https://gohugo.io/host-and-deploy/host-on-github-pages/#step-2
caches:
  images:
    dir: :cacheDir/images

# for tailwindcss
# would prefer to have this at the custom theme level, will have to look into that again
# https://gohugo.io/functions/css/tailwindcss/#step-2
build:
  buildStats:
    enable: true
  cachebusters:
    - source: "layouts/.*"
      target: css

security:
  funcs:
    getenv: ["GITHUB_SHA"]
