baseURL: https://www.apollo-roboto.dev/
languageCode: en-us
defaultContentLanguage: en
title: Apollo-Roboto
theme: customTheme

enableGitInfo: true
copyright: Apollo-Roboto
summaryLength: 70
enableEmoji: true
enableInlineShortcodes: true
googleAnalytics: G-99E0KYVB3G
rssLimit: null
paginate: 5
enableRobotsTXT: true

author:
  name: Apollo-Roboto
  email: Apollo_Roboto@outlook.com

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3

markup:
  highlight:
    noClasses: false
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

params:
  debug: false
  visualEffects: true
  pride: true
  githubIssueUrl: https://github.com/Apollo-Roboto/Apollo-Roboto.dev/issues/new/choose
  socials:
    - name: GitHub
      url: https://github.com/Apollo-Roboto
      text: Apollo-Roboto
      iconUrl: /images/GitHub_Icon.svg
    - name: StackOverflow
      url: https://stackoverflow.com/users/10101321/apollo-roboto
      text: Apollo-Roboto
      iconUrl: /images/StackOverflow_Icon.svg
    - name: LinkedIn
      url: https://www.linkedin.com/in/alexandre-thibessart-a63837181/
      text: Alexandre Thibessart
      iconUrl: /images/LinkedIn_Icon.svg
    - name: Ko-fi
      url: https://ko-fi.com/apolloroboto
      text: Buy me a coffee!
      iconUrl: /images/Ko-fi_Icon.svg
    - name: Buymeacoffee
      url: https://www.buymeacoffee.com/ApolloRoboto
      text: Buy me a coffee!
      iconUrl: /images/buymeacoffee_Icon.svg
    - name: Email
      url: mailto:Apollo_Roboto@outlook.com
      text: Apollo_Roboto@outlook.com
      iconUrl: /images/Email_Icon.svg
    - name: RSS
      url: https://www.apollo-roboto.dev/index.xml
      text: Subscribe
      iconUrl: /images/RSS_Icon.svg
