# yaml-language-server: $schema=https://www.schemastore.org/github-issue-forms.json

name: Bug Report
description: Did the site broke? Let me know!
labels:
  - bug
assignees:
  - Apollo-Roboto
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: page_url
    attributes:
      label: Page URL
      description: Where did you saw the bug?
      placeholder: https://www.apollo-roboto.dev/BUGGY_PAGE

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Firefox
        - Chrome
        - Edge
        - Safari
        - Other

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the bug on the site.
    validations:
      required: true

  - type: upload
    id: screenshots
    attributes:
      label: Upload relevant files
      description: "Drag and drop any relevant files"
    validations:
      required: false
